---
# handlers file for ansible-role-pump
- name: Restart ccurtimemon service
  service:
    name: CCURtimemon
    state: restarted

- name: Restart VOD
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - CCURmhfrm
    - CCURmhcm
    - CCURmhgs
    - CCURmhsp
    - CCURmhvp
    - CCURmhrtc
