---
# tasks file for ansible-role-pump
- name: Include vars
  include_vars:
    file: hosts.yml

- name: Set hostname in /etc/hostname
  copy:
    content: "{{ pump_hostname }}"
    dest: /etc/hostname
    force: no

- name: Change external TimeSource in CCURtimemon
  lineinfile:
    path: "{{ ccurtimemon }}"
    regexp: '^EXTERNAL_TS='
    line: 'EXTERNAL_TS={{ externalts_ip }}'
  notify: Restart ccurtimemon service

- name: Change primary TimeSource in CCURtimemon
  lineinfile:
    path: "{{ ccurtimemon }}"
    regexp: '^PRIMARY_TS='
    line: 'PRIMARY_TS={{ ansible_default_ipv4.address }}'
  notify: Restart ccurtimemon service

- name: Run ntpconfig
  command: ntpconfig /etc
  changed_when: false

- name: Flush handlers
  meta: flush_handlers

- name: Generate {{ mhresource }} file
  template:
    src=templates/resource.cfg.j2
    dest="{{ mhresource }}"
  notify: Restart VOD

- name: Make sure "{{ vodaddressmap }}" is configured
  copy:
    content: '{{ ansible_default_ipv4.network }} {{ ansible_default_ipv4.netmask }} {{ ansible_default_ipv4.address }}'
    dest: "{{ vodaddressmap }}"
    force: yes
  notify: Restart VOD

- name: Flush handlers
  meta: flush_handlers
