---
# tasks file for ansible-role-pump
- name: Include vars
  include_vars:
    file: hosts.yml

- name: Set hostname
  lineinfile:
    dest: /etc/hostname
    regexp: '^'
    line: "{{ cim_hostname }}"
    backrefs: yes

- name: Change external TimeSource in CCURtimemon
  lineinfile:
    path: "{{ ccurtimemon }}"
    regexp: '^EXTERNAL_TS='
    line: 'EXTERNAL_TS={{ externalts_ip }}'
  notify: Restart ccurtimemon service

- name: Change primary TimeSource in CCURtimemon
  lineinfile:
    path: "{{ ccurtimemon }}"
    regexp: '^PRIMARY_TS='
    line: 'PRIMARY_TS={{ pump_ip }}'
  notify: Restart ccurtimemon service

- name: Run ntpconfig
  command: ntpconfig /etc
  changed_when: false

- name: Flush handlers
  meta: flush_handlers

- name: Change Define MHSP in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Define: MHSP'
    line: 'Define: MHSP {{ pump_hostname }}'
  notify: Restart VOD

- name: Change Define MHVP in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Define: MHVP'
    line: 'Define: MHVP {{ pump_hostname }}'
  notify: Restart VOD

- name: Change Define MHRTC in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Define: MHRTC'
    line: 'Define: MHRTC {{ pump_hostname }}'
  notify: Restart VOD

- name: Change Configure MHVP in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Configure:	MHVP'
    line: 'Configure:	MHVP	{{ pump_hostname }}'
  notify: Restart VOD

- name: Change Configure MHRTC in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Configure:	MHRTC'
    line: 'Configure:	MHRTC	{{ pump_hostname }}'
  notify: Restart VOD

- name: Change Define MHRTC in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Define: MHRTC'
    line: 'Define: MHRTC {{ pump_hostname }}'
  notify: Restart VOD

- name: Change Define MHSP in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Define: MHSP'
    line: 'Define: MHSP {{ pump_hostname }}'
  notify: Restart VOD

- name: Change Define interface name in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: '^Define: IP	{{ item }}  '
    line: 'Define: IP	{{ item }}  {{ ansible_default_ipv4.interface }} 	   eth1000'
  loop:
    - control
    - egress
    - ingest
  notify: Restart VOD

- name: Change Define disk size in resource.cfg
  lineinfile:
    path: "{{ mhresource }}"
    regexp: 'Define: Disk'
    line: 'Define: Disk    1s0             /r1             VIRTUAL_1MB * 64'
  notify: Restart VOD

- name: Edit /etc/opt/MediaHawk/VODAddressMap
  lineinfile:
    path: /etc/opt/MediaHawk/VODAddressMap
    state: present
    line: '{{ ansible_default_ipv4.network }} {{ ansible_default_ipv4.netmask }} {{ ansible_default_ipv4.address }}'
  notify: Restart VOD

- name: Flush handlers
  meta: flush_handlers
