---
- hosts: all
  become: yes
  gather_facts: false
  roles:
  - { role: ansible-role-hosts, tags: hosts }

- hosts: vtsi
  become: yes
  gather_facts: false
  roles:
  - { role: ansible-role-vtsi, tags: vtsi }

- hosts: cim
  become: yes
  gather_facts: false
  roles:
  - { role: ansible-role-cim, tags: cim }

- hosts: pump
  become: yes
  gather_facts: false
  roles:
  - { role: ansible-role-pump, tags: pump }
