# name of hostnames
cim_hostname: cim
pump_hostname: pump
mdb_hostname: SPOTDB2016

# IP of hosts
cim_ip: 10.48.77.46
pump_ip: 10.48.77.47
mdb_ip: 10.48.77.48

# EXTERNAL Time Source for pump
externalts_ip: 192.168.160.158
