site_prefix: AUTOMAT2
# name of hostnames
cim_hostname: "{{ site_prefix }}CIM01"
pump_hostname: "{{ site_prefix }}PUMP01"
vtsi_hostname: "{{ site_prefix }}VTSI01"
mdb_hostname: "{{ site_prefix }}MDB01"

# IP of hosts
cim_ip: 10.48.77.52
pump_ip: 10.48.77.53
vtsi_ip: 10.48.77.56
mdb_ip: 10.48.77.49

# EXTERNAL Time Source for pump
externalts_ip: 192.168.160.158
