site_prefix: AUTOMAT
# name of hostnames
cim_hostname: cim
pump_hostname: pump
vtsi_hostname: "{{ site_prefix }}VTSI"
mdb_hostname: "{{ site_prefix }}MDB01"

# IP of hosts
cim_ip: 10.48.77.46
pump_ip: 10.48.77.47
vtsi_ip: 10.48.77.48
mdb_ip: 10.48.77.45

# EXTERNAL Time Source for pump
externalts_ip: 192.168.160.158
