site_prefix: AUTOMAT4
#name of hostnames
#
# for some reason cim and pump should be not changed as this breaks deployment, see curl  -sX GET -i http://<cim_ip>:8081/CIM/ws/Volumes
cim_hostname: "cim"
pump_hostname: "pump"
vtsi_hostname: "{{ site_prefix }}VTSI01"
mdb_hostname: "{{ site_prefix }}MDB01"

# IP of hosts
cim_ip: 10.48.77.16
pump_ip: 10.48.77.56
vtsi_ip: 10.48.77.57
mdb_ip: 10.48.77.58

# EXTERNAL Time Source for pump
externalts_ip: 192.168.160.158
