---
# handlers file for ansible-role-vtsi
- name: restart vtsi
  service:
    name: vtsi
    state: restarted
    enabled: yes

- name: start vtsi
  service:
    name: vtsi
    state: started
    enabled: yes
