---
# tasks file for ansible-role-cim
- name: Include vars
  include_vars:
    file: hosts.yml

- name: Touch hostname
  file:
    state: touch
    path: /etc/hostname
    modification_time: "preserve"
    access_time: "preserve"

- name: Set hostname
  lineinfile:
    dest: /etc/hostname
    line: "{{ cim_hostname }}"

- name: Change Library Address to PUMP IP in cim.cfg
  lineinfile:
    path: "{{ cim_config }}"
    regexp: '^Library Address: '
    line: 'Library Address: {{ pump_ip }}'
  notify: Restart services

- name: Change Virtual IP to CIM IP in cim.cfg
  lineinfile:
    path: "{{ cim_config }}"
    regexp: '^CIM Virtual IP: '
    line: 'CIM Virtual IP: {{ cim_ip }}'
  notify: Restart services

- name: Flush handlers
  meta: flush_handlers
