---
# tasks file for ansible-role-cim
- name: Include vars
  include_vars:
    file: hosts.yml

- name: Set hostname in /etc/hostname
  copy:
    content: "{{ cim_hostname }}"
    dest: /etc/hostname
    force: no

- name: Change Library Address to PUMP IP in {{ cim_config }}
  lineinfile:
    path: "{{ cim_config }}"
    regexp: '^Library Address: '
    line: 'Library Address: {{ pump_ip }}'
  notify: Restart services

- name: Change Virtual IP to CIM IP in {{ cim_config }}
  lineinfile:
    path: "{{ cim_config }}"
    regexp: '^CIM Virtual IP: '
    line: 'CIM Virtual IP: {{ cim_ip }}'
  notify: Restart services

- name: Flush handlers
  meta: flush_handlers
